server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-server
          uri: lb://MAIN-SERVER
          predicates:
            - Path=/api/v1/concerts/**, /api/v1/reservations/**, /api/v1/payments/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
